FROM node:23-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ARG WEB_HOST
ARG WEB_PLAUSIBLE_HOST
ARG WEB_DEFAULT_API

FROM base AS build
WORKDIR /app
COPY . /app

RUN corepack enable

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

RUN cd web && pnpm build

FROM base AS web
WORKDIR /app

COPY --from=build --chown=node:node /app/web/build /app

USER node

EXPOSE 3000
CMD [ "node", "index.js" ]
